###############################################################################
# General broker behavior
###############################################################################

# Global auth settings are applied to all listeners.
per_listener_settings false

# Allow zero-length client IDs.
allow_zero_length_clientid false

###############################################################################
# Persistence
###############################################################################

persistence true

persistence_location /mosquitto/data/

persistence_file mosquitto.db

autosave_interval 1800

autosave_on_changes false


###############################################################################
# Logging
###############################################################################

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

log_type error
log_type warning
log_type notice
log_type information

log_timestamp true

log_timestamp_format %Y-%m-%dT%H:%M:%S

# Include connection messages.
connection_messages true

###############################################################################
# Default listener
###############################################################################

listener 1883
protocol mqtt

allow_anonymous true

###############################################################################
# WebSocket listener
###############################################################################

listener 9001
protocol websockets

allow_anonymous true